//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MagErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MagErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdDemo.Resources.MagErrors", typeof(MagErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag Lib : No Error.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag Lib : Card Detected.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag Lib : COM not Free.
        /// </summary>
        internal static string _30 {
            get {
                return ResourceManager.GetString("-30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag Lib : Magnetic Stripe Reader not Found.
        /// </summary>
        internal static string _31 {
            get {
                return ResourceManager.GetString("-31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag Lib : Bad Parameters.
        /// </summary>
        internal static string _32 {
            get {
                return ResourceManager.GetString("-32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag Lib : Card not Detected.
        /// </summary>
        internal static string _33 {
            get {
                return ResourceManager.GetString("-33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag Lib : Serial not Initialized.
        /// </summary>
        internal static string _34 {
            get {
                return ResourceManager.GetString("-34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag Lib : Serial Port not Open.
        /// </summary>
        internal static string _35 {
            get {
                return ResourceManager.GetString("-35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag Lib : Serial Port Configuration Failed.
        /// </summary>
        internal static string _36 {
            get {
                return ResourceManager.GetString("-36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag Lib : Serial COM Timeout Failed.
        /// </summary>
        internal static string _37 {
            get {
                return ResourceManager.GetString("-37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag Lib : Serial Failed to Transmit.
        /// </summary>
        internal static string _38 {
            get {
                return ResourceManager.GetString("-38", resourceCulture);
            }
        }
    }
}
