//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PassportErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PassportErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PassportTwainScanDemo.Resources.PassportErrors", typeof(PassportErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_INTERNAL_IMAGE.
        /// </summary>
        internal static string _132 {
            get {
                return ResourceManager.GetString("-132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASS_ERR_BAD_PARAM.
        /// </summary>
        internal static string _40 {
            get {
                return ResourceManager.GetString("-40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASS_ERR_CANNOT_DELETE_DESTINATION_IMAGE.
        /// </summary>
        internal static string _41 {
            get {
                return ResourceManager.GetString("-41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASS_ERR_CANNOT_COPY_TO_DESTONATION.
        /// </summary>
        internal static string _42 {
            get {
                return ResourceManager.GetString("-42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASS_ERR_CANNOT_DELETE_DESTINATION_IMAGE.
        /// </summary>
        internal static string _43 {
            get {
                return ResourceManager.GetString("-43", resourceCulture);
            }
        }
    }
}
