//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RFIDErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RFIDErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdDemo.Resources.RFIDErrors", typeof(RFIDErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Lib : No Error.
        /// </summary>
        internal static string _0 {
            get {
                return ResourceManager.GetString("0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Lib : No RFID Reader.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Lib : RFID not Found on the Passport.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Lib : Wrong MRZ.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Lib : DG1 Process Failed.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Lib : MRDT Error - No License.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("-5", resourceCulture);
            }
        }
    }
}
